namespace Fischless.Fetch.Datas;

public static class UnuselessDataProvider
{
    public static int GetAvatarRarity(string avatarIconName)
    {
        return avatarIconName switch
        {
            "UI_AvatarIcon_Albedo" => 5,
            "UI_AvatarIcon_Alhatham" => 5,
            "UI_AvatarIcon_Aloy" => 5,
            "UI_AvatarIcon_Ambor" => 4,
            "UI_AvatarIcon_Aozi" => 4,
            "UI_AvatarIcon_Ayaka" => 5,
            "UI_AvatarIcon_Ayato" => 5,
            "UI_AvatarIcon_Baizhuer" => 5,
            "UI_AvatarIcon_Barbara" => 4,
            "UI_AvatarIcon_Beidou" => 4,
            "UI_AvatarIcon_Bennett" => 4,
            "UI_AvatarIcon_Candace" => 4,
            "UI_AvatarIcon_Chongyun" => 4,
            "UI_AvatarIcon_Collei" => 4,
            "UI_AvatarIcon_Cyno" => 5,
            "UI_AvatarIcon_Dehya" => 5,
            "UI_AvatarIcon_Diluc" => 5,
            "UI_AvatarIcon_Diona" => 4,
            "UI_AvatarIcon_Dori" => 4,
            "UI_AvatarIcon_Eula" => 5,
            "UI_AvatarIcon_Faruzan" => 4,
            "UI_AvatarIcon_Feiyan" => 4,
            "UI_AvatarIcon_Fischl" => 4,
            "UI_AvatarIcon_Freminet" => 4,
            "UI_AvatarIcon_Ganyu" => 5,
            "UI_AvatarIcon_Gorou" => 4,
            "UI_AvatarIcon_Heizo" => 4,
            "UI_AvatarIcon_Hutao" => 5,
            "UI_AvatarIcon_Itto" => 5,
            "UI_AvatarIcon_Kaeya" => 4,
            "UI_AvatarIcon_Kaveh" => 4,
            "UI_AvatarIcon_Kazuha" => 5,
            "UI_AvatarIcon_Keqing" => 5,
            "UI_AvatarIcon_Klee" => 5,
            "UI_AvatarIcon_Kokomi" => 5,
            "UI_AvatarIcon_Layla" => 4,
            "UI_AvatarIcon_Linette" => 4,
            "UI_AvatarIcon_Liney" => 5,
            "UI_AvatarIcon_Lisa" => 4,
            "UI_AvatarIcon_Mika" => 4,
            "UI_AvatarIcon_Momoka" => 4,
            "UI_AvatarIcon_Mona" => 5,
            "UI_AvatarIcon_Nahida" => 5,
            "UI_AvatarIcon_Neuvillette" => 5,
            "UI_AvatarIcon_Nilou" => 5,
            "UI_AvatarIcon_Ningguang" => 4,
            "UI_AvatarIcon_Noel" => 4,
            "UI_AvatarIcon_Paimon" => 1,
            "UI_AvatarIcon_PlayerBoy" => 5,
            "UI_AvatarIcon_PlayerGirl" => 5,
            "UI_AvatarIcon_Qin" => 5,
            "UI_AvatarIcon_Qiqi" => 5,
            "UI_AvatarIcon_Razor" => 4,
            "UI_AvatarIcon_Rosaria" => 4,
            "UI_AvatarIcon_Sara" => 4,
            "UI_AvatarIcon_Sayu" => 4,
            "UI_AvatarIcon_Shenhe" => 5,
            "UI_AvatarIcon_Shinobu" => 4,
            "UI_AvatarIcon_Shougun" => 5,
            "UI_AvatarIcon_Sucrose" => 4,
            "UI_AvatarIcon_Tartaglia" => 5,
            "UI_AvatarIcon_Tighnari" => 5,
            "UI_AvatarIcon_Tohma" => 4,
            "UI_AvatarIcon_Venti" => 5,
            "UI_AvatarIcon_Wanderer" => 5,
            "UI_AvatarIcon_Wriothesley" => 5,
            "UI_AvatarIcon_Xiangling" => 4,
            "UI_AvatarIcon_Xiao" => 5,
            "UI_AvatarIcon_Xingqiu" => 4,
            "UI_AvatarIcon_Xinyan" => 4,
            "UI_AvatarIcon_Yae" => 5,
            "UI_AvatarIcon_Yaoyao" => 4,
            "UI_AvatarIcon_Yelan" => 5,
            "UI_AvatarIcon_Yoimiya" => 5,
            "UI_AvatarIcon_Yunjin" => 4,
            "UI_AvatarIcon_Zhongli" => 5,
            _ => 1,
        };
    }
}
