name: I have a problem / 我有问题
description: Please fill in your question according to the template | 请按照模板填写你的问题
title: [question] 
labels:
  - question
body:
- type: textarea
  id: description
  validations:
    required: true
  attributes:
    label: Problem Description / 问题描述
