name: I have suggestions / 我有建议
description: Your suggestions may benefit everyone / 你的建议可能让所有人受益
title: [suggestion] 
labels:
  - suggestion
body:
- type: markdown
  attributes: 
    value: |
      > Feel free to express yourself / 请自由发挥
- type: textarea
  id: description
  validations:
    required: true
  attributes:
     label: Your suggestions / 你的建议