//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fischless.Globalization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fischless.Globalization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        public static string @__Colon__ {
            get {
                return ResourceManager.GetString("__Colon__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.
        /// </summary>
        public static string @__LeftParenthesis__ {
            get {
                return ResourceManager.GetString("__LeftParenthesis__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        public static string @__RightParenthesis__ {
            get {
                return ResourceManager.GetString("__RightParenthesis__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Program.
        /// </summary>
        public static string AboutProgram {
            get {
                return ResourceManager.GetString("AboutProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Mute.
        /// </summary>
        public static string AutoMute {
            get {
                return ResourceManager.GetString("AutoMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfAlbedo {
            get {
                return ResourceManager.GetString("AvatarNameOfAlbedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfAlhatham {
            get {
                return ResourceManager.GetString("AvatarNameOfAlhatham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfAloy {
            get {
                return ResourceManager.GetString("AvatarNameOfAloy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfAmbor {
            get {
                return ResourceManager.GetString("AvatarNameOfAmbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfAozi {
            get {
                return ResourceManager.GetString("AvatarNameOfAozi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfAyaka {
            get {
                return ResourceManager.GetString("AvatarNameOfAyaka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfAyato {
            get {
                return ResourceManager.GetString("AvatarNameOfAyato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfBaizhuer {
            get {
                return ResourceManager.GetString("AvatarNameOfBaizhuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfBarbara {
            get {
                return ResourceManager.GetString("AvatarNameOfBarbara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfBeidou {
            get {
                return ResourceManager.GetString("AvatarNameOfBeidou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfBennett {
            get {
                return ResourceManager.GetString("AvatarNameOfBennett", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfCandace {
            get {
                return ResourceManager.GetString("AvatarNameOfCandace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfCharlotte {
            get {
                return ResourceManager.GetString("AvatarNameOfCharlotte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfChongyun {
            get {
                return ResourceManager.GetString("AvatarNameOfChongyun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfCollei {
            get {
                return ResourceManager.GetString("AvatarNameOfCollei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfCyno {
            get {
                return ResourceManager.GetString("AvatarNameOfCyno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfDehya {
            get {
                return ResourceManager.GetString("AvatarNameOfDehya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfDiluc {
            get {
                return ResourceManager.GetString("AvatarNameOfDiluc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfDiona {
            get {
                return ResourceManager.GetString("AvatarNameOfDiona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfDori {
            get {
                return ResourceManager.GetString("AvatarNameOfDori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfEula {
            get {
                return ResourceManager.GetString("AvatarNameOfEula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfFaruzan {
            get {
                return ResourceManager.GetString("AvatarNameOfFaruzan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfFeiyan {
            get {
                return ResourceManager.GetString("AvatarNameOfFeiyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfFischl {
            get {
                return ResourceManager.GetString("AvatarNameOfFischl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfFreminet {
            get {
                return ResourceManager.GetString("AvatarNameOfFreminet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfFurina {
            get {
                return ResourceManager.GetString("AvatarNameOfFurina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfGanyu {
            get {
                return ResourceManager.GetString("AvatarNameOfGanyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfGorou {
            get {
                return ResourceManager.GetString("AvatarNameOfGorou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfHeizo {
            get {
                return ResourceManager.GetString("AvatarNameOfHeizo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfHutao {
            get {
                return ResourceManager.GetString("AvatarNameOfHutao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfItto {
            get {
                return ResourceManager.GetString("AvatarNameOfItto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfKaeya {
            get {
                return ResourceManager.GetString("AvatarNameOfKaeya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfKaveh {
            get {
                return ResourceManager.GetString("AvatarNameOfKaveh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfKazuha {
            get {
                return ResourceManager.GetString("AvatarNameOfKazuha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfKeqing {
            get {
                return ResourceManager.GetString("AvatarNameOfKeqing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfKlee {
            get {
                return ResourceManager.GetString("AvatarNameOfKlee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfKokomi {
            get {
                return ResourceManager.GetString("AvatarNameOfKokomi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfLayla {
            get {
                return ResourceManager.GetString("AvatarNameOfLayla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfLinette {
            get {
                return ResourceManager.GetString("AvatarNameOfLinette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfLiney {
            get {
                return ResourceManager.GetString("AvatarNameOfLiney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfLisa {
            get {
                return ResourceManager.GetString("AvatarNameOfLisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfMika {
            get {
                return ResourceManager.GetString("AvatarNameOfMika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfMomoka {
            get {
                return ResourceManager.GetString("AvatarNameOfMomoka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfMona {
            get {
                return ResourceManager.GetString("AvatarNameOfMona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfNahida {
            get {
                return ResourceManager.GetString("AvatarNameOfNahida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfNeuvillette {
            get {
                return ResourceManager.GetString("AvatarNameOfNeuvillette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfNilou {
            get {
                return ResourceManager.GetString("AvatarNameOfNilou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfNingguang {
            get {
                return ResourceManager.GetString("AvatarNameOfNingguang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfNoel {
            get {
                return ResourceManager.GetString("AvatarNameOfNoel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfPaimon {
            get {
                return ResourceManager.GetString("AvatarNameOfPaimon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfPlayerBoy {
            get {
                return ResourceManager.GetString("AvatarNameOfPlayerBoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfPlayerGirl {
            get {
                return ResourceManager.GetString("AvatarNameOfPlayerGirl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfQin {
            get {
                return ResourceManager.GetString("AvatarNameOfQin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfQiqi {
            get {
                return ResourceManager.GetString("AvatarNameOfQiqi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfRazor {
            get {
                return ResourceManager.GetString("AvatarNameOfRazor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfRosaria {
            get {
                return ResourceManager.GetString("AvatarNameOfRosaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfSara {
            get {
                return ResourceManager.GetString("AvatarNameOfSara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfSayu {
            get {
                return ResourceManager.GetString("AvatarNameOfSayu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfShenhe {
            get {
                return ResourceManager.GetString("AvatarNameOfShenhe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfShinobu {
            get {
                return ResourceManager.GetString("AvatarNameOfShinobu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfShougun {
            get {
                return ResourceManager.GetString("AvatarNameOfShougun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfSucrose {
            get {
                return ResourceManager.GetString("AvatarNameOfSucrose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfTartaglia {
            get {
                return ResourceManager.GetString("AvatarNameOfTartaglia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfTighnari {
            get {
                return ResourceManager.GetString("AvatarNameOfTighnari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfTohma {
            get {
                return ResourceManager.GetString("AvatarNameOfTohma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfUI_EquipIcon_Bow_Nachtblind_Awaken {
            get {
                return ResourceManager.GetString("AvatarNameOfUI_EquipIcon_Bow_Nachtblind_Awaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfUI_FlycloakIcon_Psalmus {
            get {
                return ResourceManager.GetString("AvatarNameOfUI_FlycloakIcon_Psalmus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfVenti {
            get {
                return ResourceManager.GetString("AvatarNameOfVenti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfWanderer {
            get {
                return ResourceManager.GetString("AvatarNameOfWanderer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfWriothesley {
            get {
                return ResourceManager.GetString("AvatarNameOfWriothesley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfXiangling {
            get {
                return ResourceManager.GetString("AvatarNameOfXiangling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfXiao {
            get {
                return ResourceManager.GetString("AvatarNameOfXiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfXingqiu {
            get {
                return ResourceManager.GetString("AvatarNameOfXingqiu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfXinyan {
            get {
                return ResourceManager.GetString("AvatarNameOfXinyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfYae {
            get {
                return ResourceManager.GetString("AvatarNameOfYae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfYaoyao {
            get {
                return ResourceManager.GetString("AvatarNameOfYaoyao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfYelan {
            get {
                return ResourceManager.GetString("AvatarNameOfYelan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfYoimiya {
            get {
                return ResourceManager.GetString("AvatarNameOfYoimiya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfYunjin {
            get {
                return ResourceManager.GetString("AvatarNameOfYunjin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvatarNameOfZhongli {
            get {
                return ResourceManager.GetString("AvatarNameOfZhongli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borderless.
        /// </summary>
        public static string Borderless {
            get {
                return ResourceManager.GetString("Borderless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borderless Game.
        /// </summary>
        public static string BorderlessHint {
            get {
                return ResourceManager.GetString("BorderlessHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string BorderlessMenu0 {
            get {
                return ResourceManager.GetString("BorderlessMenu0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Borderless Game.
        /// </summary>
        public static string BorderlessMenu1 {
            get {
                return ResourceManager.GetString("BorderlessMenu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Borderless Game.
        /// </summary>
        public static string BorderlessMenu2 {
            get {
                return ResourceManager.GetString("BorderlessMenu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Maximize button.
        /// </summary>
        public static string BorderlessMenu3 {
            get {
                return ResourceManager.GetString("BorderlessMenu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Topmost Game.
        /// </summary>
        public static string BorderlessMenu4 {
            get {
                return ResourceManager.GetString("BorderlessMenu4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Topmost Game.
        /// </summary>
        public static string BorderlessMenu5 {
            get {
                return ResourceManager.GetString("BorderlessMenu5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Screen Zero Position.
        /// </summary>
        public static string BorderlessMenu6 {
            get {
                return ResourceManager.GetString("BorderlessMenu6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Drag Move.
        /// </summary>
        public static string BorderlessMenu7 {
            get {
                return ResourceManager.GetString("BorderlessMenu7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Drag Move.
        /// </summary>
        public static string BorderlessMenu8 {
            get {
                return ResourceManager.GetString("BorderlessMenu8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CacheData {
            get {
                return ResourceManager.GetString("CacheData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CacheDataHint {
            get {
                return ResourceManager.GetString("CacheDataHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy failed.
        /// </summary>
        public static string CopyFailed {
            get {
                return ResourceManager.GetString("CopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully copied.
        /// </summary>
        public static string CopySuccessfully {
            get {
                return ResourceManager.GetString("CopySuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy version information.
        /// </summary>
        public static string CopyVersionInfo {
            get {
                return ResourceManager.GetString("CopyVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Desktop Shortcut.
        /// </summary>
        public static string CreateDesktopShortcut {
            get {
                return ResourceManager.GetString("CreateDesktopShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Failed.
        /// </summary>
        public static string CreationFailed {
            get {
                return ResourceManager.GetString("CreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DeveloperTools {
            get {
                return ResourceManager.GetString("DeveloperTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Settings.
        /// </summary>
        public static string DisplayDefault {
            get {
                return ResourceManager.GetString("DisplayDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the System Display Settings.
        /// </summary>
        public static string DisplayDefaultHint {
            get {
                return ResourceManager.GetString("DisplayDefaultHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fischless.
        /// </summary>
        public static string Fischless {
            get {
                return ResourceManager.GetString("Fischless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Settings.
        /// </summary>
        public static string GlobalSettings {
            get {
                return ResourceManager.GetString("GlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} Successfully.
        /// </summary>
        public static string LaunchGameAddAccountSuccessed {
            get {
                return ResourceManager.GetString("LaunchGameAddAccountSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGameCookieCopied {
            get {
                return ResourceManager.GetString("LaunchGameCookieCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        public static string LaunchGameDeleteAccount {
            get {
                return ResourceManager.GetString("LaunchGameDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGameDeleteAccountHint {
            get {
                return ResourceManager.GetString("LaunchGameDeleteAccountHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGamePlayingGame {
            get {
                return ResourceManager.GetString("LaunchGamePlayingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGamePleaseSelectAccountToCopy {
            get {
                return ResourceManager.GetString("LaunchGamePleaseSelectAccountToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGamePleaseSelectAccountToDelete {
            get {
                return ResourceManager.GetString("LaunchGamePleaseSelectAccountToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGamePleaseSelectAccountToEdit {
            get {
                return ResourceManager.GetString("LaunchGamePleaseSelectAccountToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择要启动的账号.
        /// </summary>
        public static string LaunchGamePleaseSelectAccountToLaunch {
            get {
                return ResourceManager.GetString("LaunchGamePleaseSelectAccountToLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGamePleaseSelectAccountToRefresh {
            get {
                return ResourceManager.GetString("LaunchGamePleaseSelectAccountToRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGameSelectAccountDisCookie {
            get {
                return ResourceManager.GetString("LaunchGameSelectAccountDisCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGameSelectAccountNoCookie {
            get {
                return ResourceManager.GetString("LaunchGameSelectAccountNoCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select {0} or {1}.
        /// </summary>
        public static string LaunchGameSelectGamePathHint {
            get {
                return ResourceManager.GetString("LaunchGameSelectGamePathHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGameSettingsEnableDetectAccountGaming {
            get {
                return ResourceManager.GetString("LaunchGameSettingsEnableDetectAccountGaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGameSettingsEnableDetectAccountGamingHint {
            get {
                return ResourceManager.GetString("LaunchGameSettingsEnableDetectAccountGamingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGameSettingsEnableLazy {
            get {
                return ResourceManager.GetString("LaunchGameSettingsEnableLazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGameSettingsEnableLazyPrivate {
            get {
                return ResourceManager.GetString("LaunchGameSettingsEnableLazyPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGameSettingsEnableReShade {
            get {
                return ResourceManager.GetString("LaunchGameSettingsEnableReShade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGameSettingsEnableReShadeSilent {
            get {
                return ResourceManager.GetString("LaunchGameSettingsEnableReShadeSilent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGameSettingsEnableReShadeSilentUAC {
            get {
                return ResourceManager.GetString("LaunchGameSettingsEnableReShadeSilentUAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGameSettingsGameBorderless {
            get {
                return ResourceManager.GetString("LaunchGameSettingsGameBorderless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGameSettingsGameFps {
            get {
                return ResourceManager.GetString("LaunchGameSettingsGameFps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGameSettingsGameFpsHint {
            get {
                return ResourceManager.GetString("LaunchGameSettingsGameFpsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGameSettingsGameFullScreen {
            get {
                return ResourceManager.GetString("LaunchGameSettingsGameFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGameSettingsGamePath {
            get {
                return ResourceManager.GetString("LaunchGameSettingsGamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGameSettingsGameResolution {
            get {
                return ResourceManager.GetString("LaunchGameSettingsGameResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGameSettingsLaunchCopyCookie {
            get {
                return ResourceManager.GetString("LaunchGameSettingsLaunchCopyCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGameSettingsLaunchCopyUID {
            get {
                return ResourceManager.GetString("LaunchGameSettingsLaunchCopyUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGameSettingsLaunchGame {
            get {
                return ResourceManager.GetString("LaunchGameSettingsLaunchGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGameSettingsLaunchGameSlow {
            get {
                return ResourceManager.GetString("LaunchGameSettingsLaunchGameSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGameSettingsLaunchGameSlowCancel {
            get {
                return ResourceManager.GetString("LaunchGameSettingsLaunchGameSlowCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGameSettingsLaunchGameSlowHint {
            get {
                return ResourceManager.GetString("LaunchGameSettingsLaunchGameSlowHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGameSettingsLaunchLazy {
            get {
                return ResourceManager.GetString("LaunchGameSettingsLaunchLazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGameSettingsLaunchReShade {
            get {
                return ResourceManager.GetString("LaunchGameSettingsLaunchReShade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGameSettingsLazy {
            get {
                return ResourceManager.GetString("LaunchGameSettingsLazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGameSettingsLazyCompleted {
            get {
                return ResourceManager.GetString("LaunchGameSettingsLazyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGameSettingsLazyNotCompleted {
            get {
                return ResourceManager.GetString("LaunchGameSettingsLazyNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LaunchGameSettingsPotentialRisks {
            get {
                return ResourceManager.GetString("LaunchGameSettingsPotentialRisks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions Settings.
        /// </summary>
        public static string LaunchGameSettingsTitle {
            get {
                return ResourceManager.GetString("LaunchGameSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your UID:{0} was copied to clipboard.
        /// </summary>
        public static string LaunchGameUidCopied {
            get {
                return ResourceManager.GetString("LaunchGameUidCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiYouShe Android.
        /// </summary>
        public static string LaunchHyperion {
            get {
                return ResourceManager.GetString("LaunchHyperion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch the MiYouShe using Windows 11 WSA (Chinese server only)..
        /// </summary>
        public static string LaunchHyperionHint {
            get {
                return ResourceManager.GetString("LaunchHyperionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LazyPleaseInputTokenHint {
            get {
                return ResourceManager.GetString("LazyPleaseInputTokenHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LazySearchRecord {
            get {
                return ResourceManager.GetString("LazySearchRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LazySearchRecordFailedHint {
            get {
                return ResourceManager.GetString("LazySearchRecordFailedHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LazySearchRecordFailedTitle {
            get {
                return ResourceManager.GetString("LazySearchRecordFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LazySetupNoTokenHint {
            get {
                return ResourceManager.GetString("LazySetupNoTokenHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LazySetupNoTokenTitle {
            get {
                return ResourceManager.GetString("LazySetupNoTokenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LazySetupToken {
            get {
                return ResourceManager.GetString("LazySetupToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LazyTestTokenFailHint {
            get {
                return ResourceManager.GetString("LazyTestTokenFailHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LazyTestTokenPassHint {
            get {
                return ResourceManager.GetString("LazyTestTokenPassHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LazyTestTokenTitle {
            get {
                return ResourceManager.GetString("LazyTestTokenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LazyTokenErrorHint {
            get {
                return ResourceManager.GetString("LazyTokenErrorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string LicenseInfo {
            get {
                return ResourceManager.GetString("LicenseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxCaptionError {
            get {
                return ResourceManager.GetString("MessageBoxCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string MessageBoxCaptionInfo {
            get {
                return ResourceManager.GetString("MessageBoxCaptionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string MessageBoxCaptionQuestion {
            get {
                return ResourceManager.GetString("MessageBoxCaptionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warn.
        /// </summary>
        public static string MessageBoxCaptionWarn {
            get {
                return ResourceManager.GetString("MessageBoxCaptionWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Viewer.
        /// </summary>
        public static string ModelViewer {
            get {
                return ResourceManager.GetString("ModelViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ModelViewerClickOrDropHint {
            get {
                return ResourceManager.GetString("ModelViewerClickOrDropHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ModelViewerSelectDMM {
            get {
                return ResourceManager.GetString("ModelViewerSelectDMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OpenUrlGameBanana {
            get {
                return ResourceManager.GetString("OpenUrlGameBanana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OpenUrlInteractiveMap {
            get {
                return ResourceManager.GetString("OpenUrlInteractiveMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OpenUrlPlayBox {
            get {
                return ResourceManager.GetString("OpenUrlPlayBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Successfully.
        /// </summary>
        public static string OperationSuccessfully {
            get {
                return ResourceManager.GetString("OperationSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Plugin {
            get {
                return ResourceManager.GetString("Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Manager.
        /// </summary>
        public static string PluginManager {
            get {
                return ResourceManager.GetString("PluginManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PluginManagerInstallNeedRestartHint {
            get {
                return ResourceManager.GetString("PluginManagerInstallNeedRestartHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PluginManagerPlugin {
            get {
                return ResourceManager.GetString("PluginManagerPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PluginManagerPluginIllegal {
            get {
                return ResourceManager.GetString("PluginManagerPluginIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PluginManagerSelectPlugin {
            get {
                return ResourceManager.GetString("PluginManagerSelectPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair Regedit.
        /// </summary>
        public static string RepairRegedit {
            get {
                return ResourceManager.GetString("RepairRegedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair Game Regedit about installtion..
        /// </summary>
        public static string RepairRegeditHint {
            get {
                return ResourceManager.GetString("RepairRegeditHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReShade.
        /// </summary>
        public static string ReShade {
            get {
                return ResourceManager.GetString("ReShade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ReShadeLoaderExeNotExists {
            get {
                return ResourceManager.GetString("ReShadeLoaderExeNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ReShadeMultiUnselectedHint {
            get {
                return ResourceManager.GetString("ReShadeMultiUnselectedHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ReShadeRemovedToRecycleBin {
            get {
                return ResourceManager.GetString("ReShadeRemovedToRecycleBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ReShadeSelectFolder {
            get {
                return ResourceManager.GetString("ReShadeSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RunLog {
            get {
                return ResourceManager.GetString("RunLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RunLogHint {
            get {
                return ResourceManager.GetString("RunLogHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Successfully.
        /// </summary>
        public static string SetSuccessfully {
            get {
                return ResourceManager.GetString("SetSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SystemEvent {
            get {
                return ResourceManager.GetString("SystemEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SystemVersion {
            get {
                return ResourceManager.GetString("SystemVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin UAC required. Do you want to restart with admin?.
        /// </summary>
        public static string UACRequestRestartHint {
            get {
                return ResourceManager.GetString("UACRequestRestartHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unneed Operate.
        /// </summary>
        public static string UnneedOperation {
            get {
                return ResourceManager.GetString("UnneedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UsefullLinks {
            get {
                return ResourceManager.GetString("UsefullLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UserManual {
            get {
                return ResourceManager.GetString("UserManual", resourceCulture);
            }
        }
    }
}
