//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fischless.Globalization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fischless.Globalization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        public static string @__Colon__ {
            get {
                return ResourceManager.GetString("__Colon__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.
        /// </summary>
        public static string @__LeftParenthesis__ {
            get {
                return ResourceManager.GetString("__LeftParenthesis__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        public static string @__RightParenthesis__ {
            get {
                return ResourceManager.GetString("__RightParenthesis__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Program.
        /// </summary>
        public static string AboutProgram {
            get {
                return ResourceManager.GetString("AboutProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Account.
        /// </summary>
        public static string AddAccount {
            get {
                return ResourceManager.GetString("AddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Permission.
        /// </summary>
        public static string AdminPermission {
            get {
                return ResourceManager.GetString("AdminPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some operations require administrator privileges.
        /// </summary>
        public static string AdminPermissionHint {
            get {
                return ResourceManager.GetString("AdminPermissionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string Alias {
            get {
                return ResourceManager.GetString("Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance and Performance.
        /// </summary>
        public static string AppearancePerformance {
            get {
                return ResourceManager.GetString("AppearancePerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize appearance and presentation.
        /// </summary>
        public static string AppearancePerformanceHint {
            get {
                return ResourceManager.GetString("AppearancePerformanceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is automatically obtained from the registry and supports global server at the same time.
        /// </summary>
        public static string AutoFromRegistryHint {
            get {
                return ResourceManager.GetString("AutoFromRegistryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Mute.
        /// </summary>
        public static string AutoMute {
            get {
                return ResourceManager.GetString("AutoMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically mute when the game window is not in the foreground state.
        /// </summary>
        public static string AutoMuteHint {
            get {
                return ResourceManager.GetString("AutoMuteHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string AvatarIcon {
            get {
                return ResourceManager.GetString("AvatarIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albedo.
        /// </summary>
        public static string AvatarNameOfAlbedo {
            get {
                return ResourceManager.GetString("AvatarNameOfAlbedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alhaitham.
        /// </summary>
        public static string AvatarNameOfAlhatham {
            get {
                return ResourceManager.GetString("AvatarNameOfAlhatham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aloy.
        /// </summary>
        public static string AvatarNameOfAloy {
            get {
                return ResourceManager.GetString("AvatarNameOfAloy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amber.
        /// </summary>
        public static string AvatarNameOfAmbor {
            get {
                return ResourceManager.GetString("AvatarNameOfAmbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oz.
        /// </summary>
        public static string AvatarNameOfAozi {
            get {
                return ResourceManager.GetString("AvatarNameOfAozi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamisato Ayaka.
        /// </summary>
        public static string AvatarNameOfAyaka {
            get {
                return ResourceManager.GetString("AvatarNameOfAyaka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamisato Ayato.
        /// </summary>
        public static string AvatarNameOfAyato {
            get {
                return ResourceManager.GetString("AvatarNameOfAyato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baizhu.
        /// </summary>
        public static string AvatarNameOfBaizhuer {
            get {
                return ResourceManager.GetString("AvatarNameOfBaizhuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbara.
        /// </summary>
        public static string AvatarNameOfBarbara {
            get {
                return ResourceManager.GetString("AvatarNameOfBarbara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beidou.
        /// </summary>
        public static string AvatarNameOfBeidou {
            get {
                return ResourceManager.GetString("AvatarNameOfBeidou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bennett.
        /// </summary>
        public static string AvatarNameOfBennett {
            get {
                return ResourceManager.GetString("AvatarNameOfBennett", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candace.
        /// </summary>
        public static string AvatarNameOfCandace {
            get {
                return ResourceManager.GetString("AvatarNameOfCandace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charlotte.
        /// </summary>
        public static string AvatarNameOfCharlotte {
            get {
                return ResourceManager.GetString("AvatarNameOfCharlotte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chongyun.
        /// </summary>
        public static string AvatarNameOfChongyun {
            get {
                return ResourceManager.GetString("AvatarNameOfChongyun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collei.
        /// </summary>
        public static string AvatarNameOfCollei {
            get {
                return ResourceManager.GetString("AvatarNameOfCollei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyno.
        /// </summary>
        public static string AvatarNameOfCyno {
            get {
                return ResourceManager.GetString("AvatarNameOfCyno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dehya.
        /// </summary>
        public static string AvatarNameOfDehya {
            get {
                return ResourceManager.GetString("AvatarNameOfDehya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diluc.
        /// </summary>
        public static string AvatarNameOfDiluc {
            get {
                return ResourceManager.GetString("AvatarNameOfDiluc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diona.
        /// </summary>
        public static string AvatarNameOfDiona {
            get {
                return ResourceManager.GetString("AvatarNameOfDiona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dori.
        /// </summary>
        public static string AvatarNameOfDori {
            get {
                return ResourceManager.GetString("AvatarNameOfDori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eula.
        /// </summary>
        public static string AvatarNameOfEula {
            get {
                return ResourceManager.GetString("AvatarNameOfEula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faruzan.
        /// </summary>
        public static string AvatarNameOfFaruzan {
            get {
                return ResourceManager.GetString("AvatarNameOfFaruzan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yanfei.
        /// </summary>
        public static string AvatarNameOfFeiyan {
            get {
                return ResourceManager.GetString("AvatarNameOfFeiyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fischl.
        /// </summary>
        public static string AvatarNameOfFischl {
            get {
                return ResourceManager.GetString("AvatarNameOfFischl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freminet.
        /// </summary>
        public static string AvatarNameOfFreminet {
            get {
                return ResourceManager.GetString("AvatarNameOfFreminet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furina.
        /// </summary>
        public static string AvatarNameOfFurina {
            get {
                return ResourceManager.GetString("AvatarNameOfFurina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ganyu.
        /// </summary>
        public static string AvatarNameOfGanyu {
            get {
                return ResourceManager.GetString("AvatarNameOfGanyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gorou.
        /// </summary>
        public static string AvatarNameOfGorou {
            get {
                return ResourceManager.GetString("AvatarNameOfGorou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shikanoin Heizou.
        /// </summary>
        public static string AvatarNameOfHeizo {
            get {
                return ResourceManager.GetString("AvatarNameOfHeizo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hu Tao.
        /// </summary>
        public static string AvatarNameOfHutao {
            get {
                return ResourceManager.GetString("AvatarNameOfHutao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arataki Itto.
        /// </summary>
        public static string AvatarNameOfItto {
            get {
                return ResourceManager.GetString("AvatarNameOfItto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaeya.
        /// </summary>
        public static string AvatarNameOfKaeya {
            get {
                return ResourceManager.GetString("AvatarNameOfKaeya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaveh.
        /// </summary>
        public static string AvatarNameOfKaveh {
            get {
                return ResourceManager.GetString("AvatarNameOfKaveh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaedehara Kazuha.
        /// </summary>
        public static string AvatarNameOfKazuha {
            get {
                return ResourceManager.GetString("AvatarNameOfKazuha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keqing.
        /// </summary>
        public static string AvatarNameOfKeqing {
            get {
                return ResourceManager.GetString("AvatarNameOfKeqing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klee.
        /// </summary>
        public static string AvatarNameOfKlee {
            get {
                return ResourceManager.GetString("AvatarNameOfKlee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sangonomiya Kokomi.
        /// </summary>
        public static string AvatarNameOfKokomi {
            get {
                return ResourceManager.GetString("AvatarNameOfKokomi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layla.
        /// </summary>
        public static string AvatarNameOfLayla {
            get {
                return ResourceManager.GetString("AvatarNameOfLayla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lynette.
        /// </summary>
        public static string AvatarNameOfLinette {
            get {
                return ResourceManager.GetString("AvatarNameOfLinette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyney.
        /// </summary>
        public static string AvatarNameOfLiney {
            get {
                return ResourceManager.GetString("AvatarNameOfLiney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisa.
        /// </summary>
        public static string AvatarNameOfLisa {
            get {
                return ResourceManager.GetString("AvatarNameOfLisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mika.
        /// </summary>
        public static string AvatarNameOfMika {
            get {
                return ResourceManager.GetString("AvatarNameOfMika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirara.
        /// </summary>
        public static string AvatarNameOfMomoka {
            get {
                return ResourceManager.GetString("AvatarNameOfMomoka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mona.
        /// </summary>
        public static string AvatarNameOfMona {
            get {
                return ResourceManager.GetString("AvatarNameOfMona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nahida.
        /// </summary>
        public static string AvatarNameOfNahida {
            get {
                return ResourceManager.GetString("AvatarNameOfNahida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuvillette.
        /// </summary>
        public static string AvatarNameOfNeuvillette {
            get {
                return ResourceManager.GetString("AvatarNameOfNeuvillette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nilou.
        /// </summary>
        public static string AvatarNameOfNilou {
            get {
                return ResourceManager.GetString("AvatarNameOfNilou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ningguang.
        /// </summary>
        public static string AvatarNameOfNingguang {
            get {
                return ResourceManager.GetString("AvatarNameOfNingguang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noelle.
        /// </summary>
        public static string AvatarNameOfNoel {
            get {
                return ResourceManager.GetString("AvatarNameOfNoel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paimon.
        /// </summary>
        public static string AvatarNameOfPaimon {
            get {
                return ResourceManager.GetString("AvatarNameOfPaimon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aether.
        /// </summary>
        public static string AvatarNameOfPlayerBoy {
            get {
                return ResourceManager.GetString("AvatarNameOfPlayerBoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lumine.
        /// </summary>
        public static string AvatarNameOfPlayerGirl {
            get {
                return ResourceManager.GetString("AvatarNameOfPlayerGirl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jean.
        /// </summary>
        public static string AvatarNameOfQin {
            get {
                return ResourceManager.GetString("AvatarNameOfQin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qiqi.
        /// </summary>
        public static string AvatarNameOfQiqi {
            get {
                return ResourceManager.GetString("AvatarNameOfQiqi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razor.
        /// </summary>
        public static string AvatarNameOfRazor {
            get {
                return ResourceManager.GetString("AvatarNameOfRazor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rosaria.
        /// </summary>
        public static string AvatarNameOfRosaria {
            get {
                return ResourceManager.GetString("AvatarNameOfRosaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kujou Sara.
        /// </summary>
        public static string AvatarNameOfSara {
            get {
                return ResourceManager.GetString("AvatarNameOfSara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayu.
        /// </summary>
        public static string AvatarNameOfSayu {
            get {
                return ResourceManager.GetString("AvatarNameOfSayu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shenhe.
        /// </summary>
        public static string AvatarNameOfShenhe {
            get {
                return ResourceManager.GetString("AvatarNameOfShenhe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuki Shinobu.
        /// </summary>
        public static string AvatarNameOfShinobu {
            get {
                return ResourceManager.GetString("AvatarNameOfShinobu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raiden Shogun.
        /// </summary>
        public static string AvatarNameOfShougun {
            get {
                return ResourceManager.GetString("AvatarNameOfShougun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucrose.
        /// </summary>
        public static string AvatarNameOfSucrose {
            get {
                return ResourceManager.GetString("AvatarNameOfSucrose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tartaglia.
        /// </summary>
        public static string AvatarNameOfTartaglia {
            get {
                return ResourceManager.GetString("AvatarNameOfTartaglia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tighnari.
        /// </summary>
        public static string AvatarNameOfTighnari {
            get {
                return ResourceManager.GetString("AvatarNameOfTighnari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoma.
        /// </summary>
        public static string AvatarNameOfTohma {
            get {
                return ResourceManager.GetString("AvatarNameOfTohma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitternachts Waltz.
        /// </summary>
        public static string AvatarNameOfUI_EquipIcon_Bow_Nachtblind_Awaken {
            get {
                return ResourceManager.GetString("AvatarNameOfUI_EquipIcon_Bow_Nachtblind_Awaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psalmus.
        /// </summary>
        public static string AvatarNameOfUI_FlycloakIcon_Psalmus {
            get {
                return ResourceManager.GetString("AvatarNameOfUI_FlycloakIcon_Psalmus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venti.
        /// </summary>
        public static string AvatarNameOfVenti {
            get {
                return ResourceManager.GetString("AvatarNameOfVenti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wanderer.
        /// </summary>
        public static string AvatarNameOfWanderer {
            get {
                return ResourceManager.GetString("AvatarNameOfWanderer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wriothesley.
        /// </summary>
        public static string AvatarNameOfWriothesley {
            get {
                return ResourceManager.GetString("AvatarNameOfWriothesley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xiangling.
        /// </summary>
        public static string AvatarNameOfXiangling {
            get {
                return ResourceManager.GetString("AvatarNameOfXiangling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xiao.
        /// </summary>
        public static string AvatarNameOfXiao {
            get {
                return ResourceManager.GetString("AvatarNameOfXiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xingqiu.
        /// </summary>
        public static string AvatarNameOfXingqiu {
            get {
                return ResourceManager.GetString("AvatarNameOfXingqiu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xinyan.
        /// </summary>
        public static string AvatarNameOfXinyan {
            get {
                return ResourceManager.GetString("AvatarNameOfXinyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yae Miko.
        /// </summary>
        public static string AvatarNameOfYae {
            get {
                return ResourceManager.GetString("AvatarNameOfYae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yaoyao.
        /// </summary>
        public static string AvatarNameOfYaoyao {
            get {
                return ResourceManager.GetString("AvatarNameOfYaoyao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yelan.
        /// </summary>
        public static string AvatarNameOfYelan {
            get {
                return ResourceManager.GetString("AvatarNameOfYelan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yoimiya.
        /// </summary>
        public static string AvatarNameOfYoimiya {
            get {
                return ResourceManager.GetString("AvatarNameOfYoimiya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yun Jin.
        /// </summary>
        public static string AvatarNameOfYunjin {
            get {
                return ResourceManager.GetString("AvatarNameOfYunjin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zhongli.
        /// </summary>
        public static string AvatarNameOfZhongli {
            get {
                return ResourceManager.GetString("AvatarNameOfZhongli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borderless.
        /// </summary>
        public static string Borderless {
            get {
                return ResourceManager.GetString("Borderless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borderless Game.
        /// </summary>
        public static string BorderlessHint {
            get {
                return ResourceManager.GetString("BorderlessHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string BorderlessMenu0 {
            get {
                return ResourceManager.GetString("BorderlessMenu0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Borderless Game.
        /// </summary>
        public static string BorderlessMenu1 {
            get {
                return ResourceManager.GetString("BorderlessMenu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Borderless Game.
        /// </summary>
        public static string BorderlessMenu2 {
            get {
                return ResourceManager.GetString("BorderlessMenu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Maximize button.
        /// </summary>
        public static string BorderlessMenu3 {
            get {
                return ResourceManager.GetString("BorderlessMenu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Topmost Game.
        /// </summary>
        public static string BorderlessMenu4 {
            get {
                return ResourceManager.GetString("BorderlessMenu4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Topmost Game.
        /// </summary>
        public static string BorderlessMenu5 {
            get {
                return ResourceManager.GetString("BorderlessMenu5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Screen Zero Position.
        /// </summary>
        public static string BorderlessMenu6 {
            get {
                return ResourceManager.GetString("BorderlessMenu6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Drag Move.
        /// </summary>
        public static string BorderlessMenu7 {
            get {
                return ResourceManager.GetString("BorderlessMenu7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Drag Move.
        /// </summary>
        public static string BorderlessMenu8 {
            get {
                return ResourceManager.GetString("BorderlessMenu8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User data.
        /// </summary>
        public static string CacheData {
            get {
                return ResourceManager.GetString("CacheData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User data recorded locally.
        /// </summary>
        public static string CacheDataHint {
            get {
                return ResourceManager.GetString("CacheDataHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Server.
        /// </summary>
        public static string ChineseServer {
            get {
                return ResourceManager.GetString("ChineseServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy failed.
        /// </summary>
        public static string CopyFailed {
            get {
                return ResourceManager.GetString("CopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully copied.
        /// </summary>
        public static string CopySuccessfully {
            get {
                return ResourceManager.GetString("CopySuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy version information.
        /// </summary>
        public static string CopyVersionInfo {
            get {
                return ResourceManager.GetString("CopyVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Desktop Shortcut.
        /// </summary>
        public static string CreateDesktopShortcut {
            get {
                return ResourceManager.GetString("CreateDesktopShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Failed.
        /// </summary>
        public static string CreationFailed {
            get {
                return ResourceManager.GetString("CreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Account.
        /// </summary>
        public static string CurrentAccount {
            get {
                return ResourceManager.GetString("CurrentAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data storage.
        /// </summary>
        public static string DataStorage {
            get {
                return ResourceManager.GetString("DataStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Folder.
        /// </summary>
        public static string DeleteFolder {
            get {
                return ResourceManager.GetString("DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desp.
        /// </summary>
        public static string Desp {
            get {
                return ResourceManager.GetString("Desp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer Tools.
        /// </summary>
        public static string DeveloperTools {
            get {
                return ResourceManager.GetString("DeveloperTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Settings.
        /// </summary>
        public static string DisplayDefault {
            get {
                return ResourceManager.GetString("DisplayDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the System Display Settings.
        /// </summary>
        public static string DisplayDefaultHint {
            get {
                return ResourceManager.GetString("DisplayDefaultHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure to restart with administrator.
        /// </summary>
        public static string EnsureRestartAdmin {
            get {
                return ResourceManager.GetString("EnsureRestartAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} not exists.
        /// </summary>
        public static string FileNotExistsHint {
            get {
                return ResourceManager.GetString("FileNotExistsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fischless.
        /// </summary>
        public static string Fischless {
            get {
                return ResourceManager.GetString("Fischless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Server.
        /// </summary>
        public static string GlobalServer {
            get {
                return ResourceManager.GetString("GlobalServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Settings.
        /// </summary>
        public static string GlobalSettings {
            get {
                return ResourceManager.GetString("GlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Settings.
        /// </summary>
        public static string GoToSettings {
            get {
                return ResourceManager.GetString("GoToSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden in tray.
        /// </summary>
        public static string HiddenInTray {
            get {
                return ResourceManager.GetString("HiddenInTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the main window and hide the automatic tray.
        /// </summary>
        public static string HiddenInTrayHint {
            get {
                return ResourceManager.GetString("HiddenInTrayHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation path.
        /// </summary>
        public static string InstallationPath {
            get {
                return ResourceManager.GetString("InstallationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Plugin.
        /// </summary>
        public static string InstallPlugin {
            get {
                return ResourceManager.GetString("InstallPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support HoYoLAB, and just access basic information.
        /// </summary>
        public static string IsUseCookieHint {
            get {
                return ResourceManager.GetString("IsUseCookieHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} Successfully.
        /// </summary>
        public static string LaunchGameAddAccountSuccessed {
            get {
                return ResourceManager.GetString("LaunchGameAddAccountSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookie copied to clipboard.
        /// </summary>
        public static string LaunchGameCookieCopied {
            get {
                return ResourceManager.GetString("LaunchGameCookieCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account.
        /// </summary>
        public static string LaunchGameDeleteAccount {
            get {
                return ResourceManager.GetString("LaunchGameDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure you want to delete account &apos;{0}&apos;?.
        /// </summary>
        public static string LaunchGameDeleteAccountHint {
            get {
                return ResourceManager.GetString("LaunchGameDeleteAccountHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing.
        /// </summary>
        public static string LaunchGamePlayingGame {
            get {
                return ResourceManager.GetString("LaunchGamePlayingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the account wana copy.
        /// </summary>
        public static string LaunchGamePleaseSelectAccountToCopy {
            get {
                return ResourceManager.GetString("LaunchGamePleaseSelectAccountToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the account wana delete.
        /// </summary>
        public static string LaunchGamePleaseSelectAccountToDelete {
            get {
                return ResourceManager.GetString("LaunchGamePleaseSelectAccountToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the account wana edit.
        /// </summary>
        public static string LaunchGamePleaseSelectAccountToEdit {
            get {
                return ResourceManager.GetString("LaunchGamePleaseSelectAccountToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the account wana launch.
        /// </summary>
        public static string LaunchGamePleaseSelectAccountToLaunch {
            get {
                return ResourceManager.GetString("LaunchGamePleaseSelectAccountToLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the account wana refresh.
        /// </summary>
        public static string LaunchGamePleaseSelectAccountToRefresh {
            get {
                return ResourceManager.GetString("LaunchGamePleaseSelectAccountToRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected account is not enabled for cookie usage.
        /// </summary>
        public static string LaunchGameSelectAccountDisCookie {
            get {
                return ResourceManager.GetString("LaunchGameSelectAccountDisCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected account has no cookie information.
        /// </summary>
        public static string LaunchGameSelectAccountNoCookie {
            get {
                return ResourceManager.GetString("LaunchGameSelectAccountNoCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select {0} or {1}.
        /// </summary>
        public static string LaunchGameSelectGamePathHint {
            get {
                return ResourceManager.GetString("LaunchGameSelectGamePathHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s take an alias first.
        /// </summary>
        public static string LaunchGameSettingsAliasNamingHint {
            get {
                return ResourceManager.GetString("LaunchGameSettingsAliasNamingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable account recognition.
        /// </summary>
        public static string LaunchGameSettingsEnableDetectAccountGaming {
            get {
                return ResourceManager.GetString("LaunchGameSettingsEnableDetectAccountGaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very intelligent but consumes a small amount of resources for polling detection.
        /// </summary>
        public static string LaunchGameSettingsEnableDetectAccountGamingHint {
            get {
                return ResourceManager.GetString("LaunchGameSettingsEnableDetectAccountGamingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Lazy.
        /// </summary>
        public static string LaunchGameSettingsEnableLazy {
            get {
                return ResourceManager.GetString("LaunchGameSettingsEnableLazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string LaunchGameSettingsEnableLazyPrivate {
            get {
                return ResourceManager.GetString("LaunchGameSettingsEnableLazyPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable ReShade.
        /// </summary>
        public static string LaunchGameSettingsEnableReShade {
            get {
                return ResourceManager.GetString("LaunchGameSettingsEnableReShade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silent Mode.
        /// </summary>
        public static string LaunchGameSettingsEnableReShadeSilent {
            get {
                return ResourceManager.GetString("LaunchGameSettingsEnableReShadeSilent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs UAC Permissions.
        /// </summary>
        public static string LaunchGameSettingsEnableReShadeSilentUAC {
            get {
                return ResourceManager.GetString("LaunchGameSettingsEnableReShadeSilentUAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Cookie.
        /// </summary>
        public static string LaunchGameSettingsEnterCookieHint {
            get {
                return ResourceManager.GetString("LaunchGameSettingsEnterCookieHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borderless.
        /// </summary>
        public static string LaunchGameSettingsGameBorderless {
            get {
                return ResourceManager.GetString("LaunchGameSettingsGameBorderless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock FPS.
        /// </summary>
        public static string LaunchGameSettingsGameFps {
            get {
                return ResourceManager.GetString("LaunchGameSettingsGameFps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusting FPS through injection into rendering engines.
        /// </summary>
        public static string LaunchGameSettingsGameFpsHint {
            get {
                return ResourceManager.GetString("LaunchGameSettingsGameFpsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullScreen.
        /// </summary>
        public static string LaunchGameSettingsGameFullScreen {
            get {
                return ResourceManager.GetString("LaunchGameSettingsGameFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Path.
        /// </summary>
        public static string LaunchGameSettingsGamePath {
            get {
                return ResourceManager.GetString("LaunchGameSettingsGamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        public static string LaunchGameSettingsGameResolution {
            get {
                return ResourceManager.GetString("LaunchGameSettingsGameResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Cookie.
        /// </summary>
        public static string LaunchGameSettingsLaunchCopyCookie {
            get {
                return ResourceManager.GetString("LaunchGameSettingsLaunchCopyCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy UID.
        /// </summary>
        public static string LaunchGameSettingsLaunchCopyUID {
            get {
                return ResourceManager.GetString("LaunchGameSettingsLaunchCopyUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Game.
        /// </summary>
        public static string LaunchGameSettingsLaunchGame {
            get {
                return ResourceManager.GetString("LaunchGameSettingsLaunchGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Game Slowly.
        /// </summary>
        public static string LaunchGameSettingsLaunchGameSlow {
            get {
                return ResourceManager.GetString("LaunchGameSettingsLaunchGameSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Launch Game Slowly.
        /// </summary>
        public static string LaunchGameSettingsLaunchGameSlowCancel {
            get {
                return ResourceManager.GetString("LaunchGameSettingsLaunchGameSlowCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the selected account in 3 minutes.
        /// </summary>
        public static string LaunchGameSettingsLaunchGameSlowHint {
            get {
                return ResourceManager.GetString("LaunchGameSettingsLaunchGameSlowHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start component.
        /// </summary>
        public static string LaunchGameSettingsLaunchLazy {
            get {
                return ResourceManager.GetString("LaunchGameSettingsLaunchLazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate the ReShade.
        /// </summary>
        public static string LaunchGameSettingsLaunchReShade {
            get {
                return ResourceManager.GetString("LaunchGameSettingsLaunchReShade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open ReShade Folder.
        /// </summary>
        public static string LaunchGameSettingsLaunchReShadeFolder {
            get {
                return ResourceManager.GetString("LaunchGameSettingsLaunchReShadeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily World Quest.
        /// </summary>
        public static string LaunchGameSettingsLazy {
            get {
                return ResourceManager.GetString("LaunchGameSettingsLazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest completed.
        /// </summary>
        public static string LaunchGameSettingsLazyCompleted {
            get {
                return ResourceManager.GetString("LaunchGameSettingsLazyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest incomplete.
        /// </summary>
        public static string LaunchGameSettingsLazyNotCompleted {
            get {
                return ResourceManager.GetString("LaunchGameSettingsLazyNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential Risks.
        /// </summary>
        public static string LaunchGameSettingsPotentialRisks {
            get {
                return ResourceManager.GetString("LaunchGameSettingsPotentialRisks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions Settings.
        /// </summary>
        public static string LaunchGameSettingsTitle {
            get {
                return ResourceManager.GetString("LaunchGameSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your UID:{0} was copied to clipboard.
        /// </summary>
        public static string LaunchGameUidCopied {
            get {
                return ResourceManager.GetString("LaunchGameUidCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HoYoLAB Android.
        /// </summary>
        public static string LaunchHyperion {
            get {
                return ResourceManager.GetString("LaunchHyperion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch HoYoLAB by Win11 WSA (Chinese only).
        /// </summary>
        public static string LaunchHyperionHint {
            get {
                return ResourceManager.GetString("LaunchHyperionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt token.
        /// </summary>
        public static string LazyEncryptToken {
            get {
                return ResourceManager.GetString("LazyEncryptToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: An encryption token is auto generated after you enter the token.
        /// </summary>
        public static string LazyEncryptTokenHint {
            get {
                return ResourceManager.GetString("LazyEncryptTokenHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Token.
        /// </summary>
        public static string LazyOpenToken {
            get {
                return ResourceManager.GetString("LazyOpenToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a token.
        /// </summary>
        public static string LazyPleaseInputTokenHint {
            get {
                return ResourceManager.GetString("LazyPleaseInputTokenHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Record.
        /// </summary>
        public static string LazySearchRecord {
            get {
                return ResourceManager.GetString("LazySearchRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure that the server token path is correct and try again.
        /// </summary>
        public static string LazySearchRecordFailedHint {
            get {
                return ResourceManager.GetString("LazySearchRecordFailedHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Record failed.
        /// </summary>
        public static string LazySearchRecordFailedTitle {
            get {
                return ResourceManager.GetString("LazySearchRecordFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Time.
        /// </summary>
        public static string LazySearchRecordTime {
            get {
                return ResourceManager.GetString("LazySearchRecordTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Today.
        /// </summary>
        public static string LazySearchRecordToday {
            get {
                return ResourceManager.GetString("LazySearchRecordToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please refer to the component instructions and set the token and try again.
        /// </summary>
        public static string LazySetupNoTokenHint {
            get {
                return ResourceManager.GetString("LazySetupNoTokenHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No accessable server token detected.
        /// </summary>
        public static string LazySetupNoTokenTitle {
            get {
                return ResourceManager.GetString("LazySetupNoTokenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Token.
        /// </summary>
        public static string LazySetupToken {
            get {
                return ResourceManager.GetString("LazySetupToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test failed: incorrect token or poor network environment.
        /// </summary>
        public static string LazyTestTokenFailHint {
            get {
                return ResourceManager.GetString("LazyTestTokenFailHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test passed: took {0} milliseconds.
        /// </summary>
        public static string LazyTestTokenPassHint {
            get {
                return ResourceManager.GetString("LazyTestTokenPassHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test server token.
        /// </summary>
        public static string LazyTestTokenTitle {
            get {
                return ResourceManager.GetString("LazyTestTokenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Error.
        /// </summary>
        public static string LazyTokenErrorHint {
            get {
                return ResourceManager.GetString("LazyTokenErrorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave it blank means that you only launch the game without switching account.
        /// </summary>
        public static string LeaveAccountBlankMeanHint {
            get {
                return ResourceManager.GetString("LeaveAccountBlankMeanHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can leave it blank here.
        /// </summary>
        public static string LeaveItBlankOkay {
            get {
                return ResourceManager.GetString("LeaveItBlankOkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string LicenseInfo {
            get {
                return ResourceManager.GetString("LicenseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxCaptionError {
            get {
                return ResourceManager.GetString("MessageBoxCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string MessageBoxCaptionInfo {
            get {
                return ResourceManager.GetString("MessageBoxCaptionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string MessageBoxCaptionQuestion {
            get {
                return ResourceManager.GetString("MessageBoxCaptionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warn.
        /// </summary>
        public static string MessageBoxCaptionWarn {
            get {
                return ResourceManager.GetString("MessageBoxCaptionWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Viewer.
        /// </summary>
        public static string ModelViewer {
            get {
                return ResourceManager.GetString("ModelViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to select a DMM file or drop down it here ....
        /// </summary>
        public static string ModelViewerClickOrDropHint {
            get {
                return ResourceManager.GetString("ModelViewerClickOrDropHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a MMD model file.
        /// </summary>
        public static string ModelViewerSelectMMD {
            get {
                return ResourceManager.GetString("ModelViewerSelectMMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification and Behavior.
        /// </summary>
        public static string NotificationBehavior {
            get {
                return ResourceManager.GetString("NotificationBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize notifications and behaviors.
        /// </summary>
        public static string NotificationBehaviorHint {
            get {
                return ResourceManager.GetString("NotificationBehaviorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official.
        /// </summary>
        public static string Official {
            get {
                return ResourceManager.GetString("Official", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only show in effect.
        /// </summary>
        public static string OnlyShowInEffect {
            get {
                return ResourceManager.GetString("OnlyShowInEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Banana.
        /// </summary>
        public static string OpenUrlGameBanana {
            get {
                return ResourceManager.GetString("OpenUrlGameBanana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teyvat Map.
        /// </summary>
        public static string OpenUrlInteractiveMap {
            get {
                return ResourceManager.GetString("OpenUrlInteractiveMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Box.
        /// </summary>
        public static string OpenUrlPlayBox {
            get {
                return ResourceManager.GetString("OpenUrlPlayBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Failed.
        /// </summary>
        public static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Successfully.
        /// </summary>
        public static string OperationSuccessfully {
            get {
                return ResourceManager.GetString("OperationSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personality background.
        /// </summary>
        public static string PersonalityBackground {
            get {
                return ResourceManager.GetString("PersonalityBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the background displayed in the application.
        /// </summary>
        public static string PersonalityBackgroundHint {
            get {
                return ResourceManager.GetString("PersonalityBackgroundHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.
        /// </summary>
        public static string Plugin {
            get {
                return ResourceManager.GetString("Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Folder.
        /// </summary>
        public static string PluginFolder {
            get {
                return ResourceManager.GetString("PluginFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Manager.
        /// </summary>
        public static string PluginManager {
            get {
                return ResourceManager.GetString("PluginManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take effect after App Restart. Restarted immediately?.
        /// </summary>
        public static string PluginManagerInstallNeedRestartHint {
            get {
                return ResourceManager.GetString("PluginManagerInstallNeedRestartHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.
        /// </summary>
        public static string PluginManagerPlugin {
            get {
                return ResourceManager.GetString("PluginManagerPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal Plugin.
        /// </summary>
        public static string PluginManagerPluginIllegal {
            get {
                return ResourceManager.GetString("PluginManagerPluginIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Plugin.
        /// </summary>
        public static string PluginManagerSelectPlugin {
            get {
                return ResourceManager.GetString("PluginManagerSelectPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Market.
        /// </summary>
        public static string PluginMarket {
            get {
                return ResourceManager.GetString("PluginMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string PreviewVersion {
            get {
                return ResourceManager.GetString("PreviewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomly.
        /// </summary>
        public static string RandomlyGenerated {
            get {
                return ResourceManager.GetString("RandomlyGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reacquire.
        /// </summary>
        public static string Reacquire {
            get {
                return ResourceManager.GetString("Reacquire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognizable naming.
        /// </summary>
        public static string RecognizableNaming {
            get {
                return ResourceManager.GetString("RecognizableNaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry path.
        /// </summary>
        public static string RegistryPath {
            get {
                return ResourceManager.GetString("RegistryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Folder.
        /// </summary>
        public static string RenameFolder {
            get {
                return ResourceManager.GetString("RenameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair Regedit.
        /// </summary>
        public static string RepairRegedit {
            get {
                return ResourceManager.GetString("RepairRegedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair Game Regedit about installtion..
        /// </summary>
        public static string RepairRegeditHint {
            get {
                return ResourceManager.GetString("RepairRegeditHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReShade.
        /// </summary>
        public static string ReShade {
            get {
                return ResourceManager.GetString("ReShade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Not Exists.
        /// </summary>
        public static string ReShadeLoaderExeNotExists {
            get {
                return ResourceManager.GetString("ReShadeLoaderExeNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to disable {0} selection(s) in the current list?.
        /// </summary>
        public static string ReShadeMultiUnselectedHint {
            get {
                return ResourceManager.GetString("ReShadeMultiUnselectedHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted to the Recycle Bin.
        /// </summary>
        public static string ReShadeRemovedToRecycleBin {
            get {
                return ResourceManager.GetString("ReShadeRemovedToRecycleBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select 3DMigoto Folder.
        /// </summary>
        public static string ReShadeSelectFolder {
            get {
                return ResourceManager.GetString("ReShadeSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application logs.
        /// </summary>
        public static string RunLog {
            get {
                return ResourceManager.GetString("RunLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application log recorded locally.
        /// </summary>
        public static string RunLogHint {
            get {
                return ResourceManager.GetString("RunLogHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Genshin Impact Directory.
        /// </summary>
        public static string SelectGenshinImpactDirectory {
            get {
                return ResourceManager.GetString("SelectGenshinImpactDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serve.
        /// </summary>
        public static string Serve {
            get {
                return ResourceManager.GetString("Serve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Successfully.
        /// </summary>
        public static string SetSuccessfully {
            get {
                return ResourceManager.GetString("SetSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut.
        /// </summary>
        public static string Shortcut {
            get {
                return ResourceManager.GetString("Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide.
        /// </summary>
        public static string Slide {
            get {
                return ResourceManager.GetString("Slide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small size.
        /// </summary>
        public static string SmallSize {
            get {
                return ResourceManager.GetString("SmallSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable small default size for the main window.
        /// </summary>
        public static string SmallSizeHint {
            get {
                return ResourceManager.GetString("SmallSizeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup with system.
        /// </summary>
        public static string StartupWithSystem {
            get {
                return ResourceManager.GetString("StartupWithSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After system startup up, it will auto start in the background.
        /// </summary>
        public static string StartupWithSystemHint {
            get {
                return ResourceManager.GetString("StartupWithSystemHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Event.
        /// </summary>
        public static string SystemEvent {
            get {
                return ResourceManager.GetString("SystemEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Version.
        /// </summary>
        public static string SystemVersion {
            get {
                return ResourceManager.GetString("SystemVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme colors.
        /// </summary>
        public static string ThemeColor {
            get {
                return ResourceManager.GetString("ThemeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the color displayed in the application.
        /// </summary>
        public static string ThemeColorHint {
            get {
                return ResourceManager.GetString("ThemeColorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme cursor.
        /// </summary>
        public static string ThemeCursor {
            get {
                return ResourceManager.GetString("ThemeCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable application theme cursor.
        /// </summary>
        public static string ThemeCursorHint {
            get {
                return ResourceManager.GetString("ThemeCursorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme font.
        /// </summary>
        public static string ThemeFont {
            get {
                return ResourceManager.GetString("ThemeFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable application theme font family.
        /// </summary>
        public static string ThemeFontHint {
            get {
                return ResourceManager.GetString("ThemeFontHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin UAC required. Do you want to restart with admin?.
        /// </summary>
        public static string UACRequestRestartHint {
            get {
                return ResourceManager.GetString("UACRequestRestartHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unneed Operate.
        /// </summary>
        public static string UnneedOperation {
            get {
                return ResourceManager.GetString("UnneedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usefull Links.
        /// </summary>
        public static string UsefullLinks {
            get {
                return ResourceManager.GetString("UsefullLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Manual.
        /// </summary>
        public static string UserManual {
            get {
                return ResourceManager.GetString("UserManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
